"""Initial migration.

Revision ID: f3c928185916
Revises: 
Create Date: 2025-01-19 15:38:32.626060

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f3c928185916'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('director', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_director_name', ['name'])

    with op.batch_alter_table('genre', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_genre_name', ['name'])

    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.alter_column('title',
                              existing_type=sa.VARCHAR(length=255),
                              nullable=False)
        batch_op.alter_column('description',
                              existing_type=sa.VARCHAR(length=255),
                              nullable=False)
        batch_op.alter_column('trailer',
                              existing_type=sa.VARCHAR(length=255),
                              nullable=False)
        batch_op.alter_column('year',
                              existing_type=sa.INTEGER(),
                              nullable=False)
        batch_op.alter_column('rating',
                              existing_type=sa.FLOAT(),
                              nullable=False)
        batch_op.alter_column('genre_id',
                              existing_type=sa.INTEGER(),
                              nullable=False)
        batch_op.alter_column('director_id',
                              existing_type=sa.INTEGER(),
                              nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_name', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_name', type_='unique')

    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.alter_column('director_id',
                              existing_type=sa.INTEGER(),
                              nullable=True)
        batch_op.alter_column('genre_id',
                              existing_type=sa.INTEGER(),
                              nullable=True)
        batch_op.alter_column('rating',
                              existing_type=sa.FLOAT(),
                              nullable=True)
        batch_op.alter_column('year',
                              existing_type=sa.INTEGER(),
                              nullable=True)
        batch_op.alter_column('trailer',
                              existing_type=sa.VARCHAR(length=255),
                              nullable=True)
        batch_op.alter_column('description',
                              existing_type=sa.VARCHAR(length=255),
                              nullable=True)
        batch_op.alter_column('title',
                              existing_type=sa.VARCHAR(length=255),
                              nullable=True)

    with op.batch_alter_table('genre', schema=None) as batch_op:
        batch_op.drop_constraint('uq_genre_name', type_='unique')

    with op.batch_alter_table('director', schema=None) as batch_op:
        batch_op.drop_constraint('uq_genre_name', type_='unique')

    # ### end Alembic commands ###
